tabUI_dataAccess <- function(id){
  ns <- NS(id)

  tagList(
    bslib::card(
      bslib::card_header("ARK Portal Data Access"),
      bslib::card_body(
        tags$p(
          "The data for this publication are available through the ",
          tags$strong("Arthritis, Autoimmune, and Related Diseases Knowledge (ARK) Portal"),
          " (",
          tags$a(
            href = "http://arkportal.synapse.org",
            target = "_blank",
            rel = "noopener noreferrer",
            "arkportal.synapse.org"
          ),
          ") under the DOI: ",
          tags$a(
            href = "https://doi.org/10.7303/syn71964948.1",
            target = "_blank",
            rel = "noopener noreferrer",
            "10.7303/syn71964948.1"
          ),
          "."
        ),
        tags$p(
          "The ARK Portal hosts data generated by a network of research teams working collaboratively to deepen the understanding of Arthritis and Autoimmune and Related Diseases. It was established by the National Institute of Arthritis and Musculoskeletal and Skin Diseases (NIAMS) and includes data from the Accelerating Medicines Partnership® (AMP®) RA/SLE program."
        ),
        tags$div(
          class = "d-flex flex-wrap gap-2",
          tags$a(
            href = "http://arkportal.synapse.org",
            class = "btn btn-primary",
            target = "_blank",
            rel = "noopener noreferrer",
            "Open ARK Portal"
          ),
          tags$a(
            href = "https://doi.org/10.7303/syn71964948.1",
            class = "btn btn-outline-secondary",
            target = "_blank",
            rel = "noopener noreferrer",
            "View DOI record"
          )
        )
      )
    ),
    tags$div(
      class = "mt-3",
      layout_column_wrap(
        width = 1 / 2,
        bslib::card(
          bslib::card_header("Access requirements"),
          bslib::card_body(
            tags$p("The specific data used in this publication are available as a controlled-access dataset. Researchers seeking to use these data must submit:"),
            tags$ul(
              tags$li("A detailed intended data use statement"),
              tags$li("A completed and signed data use certificate")
            ),
            tags$span(class = "badge bg-warning text-dark", "Controlled access")
          )
        ),
        bslib::card(
          bslib::card_header("How to request access"),
          bslib::card_body(
            tags$p("Instructions for access are available at the ARK Portal help site."),
            tags$a(
              href = "https://help.arkportal.org/help/data-use-certificate#DataUse&Acknowledgement-Acknowledgement",
              class = "btn btn-outline-primary",
              target = "_blank",
              rel = "noopener noreferrer",
              "Read access instructions"
            )
          )
        )
      )
    )
  )
}

tabServer_dataAccess <- function(id, data_path){
    
}
